info:
  title: "Room4"
  description: "Room 4 test work"
  version: "0.1"
swagger: "2.0"
paths:
  /mutation/createUser:
    post:
      summary: Creates a user
      parameters:
        - in: "body"
          name: "userInput"
          required: true
          schema:
            $ref: "#definitions/UserCreateData"
      responses:
        200:
          description: "successfully operation"
  /graphql:
    post:
      summary: Creates a user
      parameters:
        - in: "body"
          name: "userInput"
          required: true
          schema:
            $ref: "#definitions/UserCreateData"
      responses:
        200:
          description: "successfully operation"
definitions:
  UserCreateData:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      login:
        type: string
      password:
        type: string
    required:
      - login
      - password